[WIP] Changelog and version number updates
xpsi-group/xpsi pull request #499
Opened 2024-12-16 17:32 UTC by thjsal

2024-12-17 09:53 UTC, MHoogkamer requested changes
"Updated the installation instructions for Helios and the example job script." should be "Helios and Snellius". Otherwise looks good to me!

2024-12-17 11:02 UTC, thjsal commented
> "Updated the installation instructions for Helios and the example job script." should be "Helios and Snellius". Otherwise looks good to me!

Sure. I have now added that.

2024-12-17 13:00 UTC, MHoogkamer approved these changes

2024-12-17 14:06 UTC, thjsal commented
I have now rerun 2 tutorials to the update version number in them. Also fixed the SBI notebook to use the proper path to the example main module, and removed the sentence `Make sure to run this first (python examples/examples_fast/Modules.main.py), to get all output files needed to execute this notebook.`, because that is not needed (all the files are already in GitHub).

2024-12-19 09:11 UTC, drannawatts approved these changes

2024-12-19 09:50 UTC, merged